### ISSUE TITLE
Migrate lyo.tools over here

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#1]
Then I will be able to update the build config.

**Comment by jadelkhoury** [comment]
@berezovskyi what exactly do you want me to do here? i thought this is done by the Eclipse team. 
but before we  migrate, i would like to close all patches that are submitted for review first. they are not many.

**Comment by berezovskyi** [comment]
You do a git push here once you are ready to move. Eclipse folks just create the repos for us.

**Comment by jadelkhoury** [comment]
I see. 
How about the reported bugs on Bugzilla? Are we eventually moving them all to corresponding repo on  GitHub? 
Do I do that for tools, or we do for all repos later?

**Comment by jadelkhoury** [comment]
My plan for the migration:
1. merge this pull request on lyo.domains  https://github.com/eclipse/lyo.domains/pull/3 (@berezovskyi @jamsden please review)
2. merge this patch from gerrit https://git.eclipse.org/r/#/c/123705/ (once above merge is done first).

**Comment by berezovskyi** [comment]
The first part is done.

**Comment by jadelkhoury** [comment]
@berezovskyi So, is that it?
I added a remote to this github repo, then I pushed the master from the eclipse repo to github!
Do we need to lock/close down the original one? Anything else?

**Comment by berezovskyi** [comment]
why is the https://github.com/eclipse/lyo.designer/tree/master/org.eclipse.lyo.tools.domainmodels still here?

**Comment by jadelkhoury** [comment]
The model contains a comment element that says we have moved the project to a new repo.
Otherwise, users that do a pull on the repo will simply see their domainmodels project disappear.

**Comment by berezovskyi** [comment]
Then we consider the migration done. Please reopen if I missed anything.
