### ISSUE TITLE
Lyo Designer tries to generate code for external domains

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#120]
I am generating a toolchain that uses shapes from lyo.domains and the generator tries to generate their code:

![image](https://user-images.githubusercontent.com/64734/61999867-09285a80-b0cb-11e9-891e-807bd6439f37.png)

Just. Don't. Pretty please 🙏

**Comment by jadelkhoury** [comment]
it should not be. Is it only the DomainConstant classes, or even resources? 
If only DomainConstants, it could be a bug.
But I am very sure it should not be generating the resources.

**Comment by berezovskyi** [comment]
This is the full list of the files generated:

![image](https://user-images.githubusercontent.com/64734/61999946-683a9f00-b0cc-11e9-9aab-47f128c4f2c9.png)

**Comment by berezovskyi** [comment]
It seems to be generating the resources that are referenced in the toolchain model.

**Comment by jadelkhoury** [comment]
Ah yes! it does generate them. You just have to place your projects in the right path, and configure the generation paths, so that the classes are generated in the right place.

As discussed in other issues, we need to settle how/when we generate, when using composed models.

**Comment by berezovskyi** [comment]
No thanks :) I just ignored that code: https://github.com/OSLC/refimpl/blob/master/.gitignore#L4

That's because I want to rely on classes from lyo.domains JAR.

**Comment by berezovskyi** [comment]
I think it's best to mark domain specs as internal (external by default) so that some specs can check that checkbox if they are not providing JARs (which should be assumed to be the default in 2019).

**Comment by jadelkhoury** [comment]
I believe this issue is also closed. @berezovskyi ? There is now a flag on the adaptorInterface to tell the generator NOT to generate from imported models.

**Comment by berezovskyi** [comment]
Thanks! I will reopen if this happens to me again on the edge.
