### ISSUE TITLE
Do not print a long stacktrace when developer throws a WebApplicationException

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#125]
WebApplicationException is not an exceptional case in the execution of the program, but a way to control flow. Thus, I don't want to see a long stack trace when I throw `WebApplicationException(Response.Status.BAD_REQUEST)`, especially I might have already logged the problem in the data.

**Comment by jadelkhoury** [comment]
As usual, can you please give me a link to a location in the code? either in LyoDesigner, or in your own adaptor.

**Comment by berezovskyi** [comment]
It’s the methods that call Manager’s methods. I throw an exception when aResource is null. I saw e.printStacktrace in the exception handling of those calls.

--
/Andrew
(from phone)

24 sep. 2019 kl. 09:08 skrev Jad El-khoury <notifications@github.com<mailto:notifications@github.com>>:


As usual, can you please give me a link to a location in the code? either in LyoDesigner, or in your own adaptor.

**Comment by berezovskyi** [comment]
I am further not convinced you even need an exception handler there: https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl#L328

The printing line is this one: https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl#L364
