### ISSUE TITLE
Problematic vocabulary names when inexact namespace is provided

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.designer#129]
**Scenario:** 

In the model, the namespace is defined as "http://my.space.com/ts", and then we have a shape/class named "somename"
Then,  the generator simply concatenate these 2 strings to produce the full name, which then becomes "http://my.space.com/tssomename".

Surely, the intention is to have "http://my.space.com/ts/somename" or "http://my.space.com#tssomename".

**Workaround**: Make sure you add "#" or "/" to the end of the namespace.

**Solution**:
Change generator logic so that "x" is appended to end of namespace, if namespace does not end with either "/" or "#". 

@jamsden @berezovskyi What should "x" be? "/" or "#"? I am thinking "#".

**Comment by berezovskyi** [comment]
Solution: throw an error if the namespace does not end with a slash or a hash. We don’t need more magic.

--
Andrew

________________________________

**Comment by jadelkhoury** [comment]
Did we land somewhere on this request? 
@jposterloh?

**Comment by berezovskyi** [comment]
It's a debug interface. Let's show the full URI? I am also OK with shortening the URIs with `#` because there is no risk there but not for the URIs with a `/` only. I think the less we hide in this UI, the more our users learn about Linked Data along the way.

**Comment by berezovskyi** [comment]
@jposterloh, what's your take on this?

**Comment by jadelkhoury** [comment]
> It's a debug interface. Let's show the full URI? I am also OK with shortening the URIs with `#` because there is no risk there but not for the URIs with a `/` only. I think the less we hide in this UI, the more our users learn about Linked Data along the way.

Showing the full URI will be hiding the problem, since we're no really showing the difference between the namespace, and the localname. The URI is still what is in the href link. Truncating on # or / will att least highligh if the name does not match what the modeller really intended.

**Comment by jposterloh** [comment]
Hi,

Am 17.11.2019 um 12:59 schrieb Jad El-khoury:
>
>     It's a debug interface. Let's show the full URI? I am also OK with
>     shortening the URIs with |#| because there is no risk there but
>     not for the URIs with a |/| only. I think the less we hide in this
>     UI, the more our users learn about Linked Data along the way.
>
> Showing the full URI will be hiding the problem, since we're no really
> showing the difference between the namespace, and the localname. The
> URI is still what is in the href link. Truncating on # or / will att
> least highligh if the name does not match what the modeller really
> intended.
>

As long as there is a proper error message, or the website does not
crash if someone does not use the '#', I'm fine with everything.

Best
Jan-Patrick



-- 
Dipl. Inform. Jan-Patrick Osterloh
Senior Research Engineer
Human Centered Design Group

OFFIS e.V. - Institut für Informatik | Institute for Information Technology
             FuE Bereich Verkehr     | R&D Division Transportation
             Escherweg 2, 26121 Oldenburg - Germany
Room:        D107
Phone/Fax:   +49 441 97 22-524 / -502
E-Mail:      osterloh@offis.de
URL:         http://www.offis.de 

Registergericht: Amtsgericht Oldenburg VR 1956
Vorstand: Prof. Dr.-Ing. Wolfgang H. Nebel (Vorsitzender),
          Prof. Dr. techn. Susanne Boll-Westermann,
          Prof. Dr.-Ing. Axel Hahn,
          Prof. Dr.-Ing. Andreas Hein,
          Prof. Dr. Sebastian Lehnhoff 

Unsere Hinweise zum Datenschutz sind abrufbar unter: 
https://www.offis.de/datentransparenz.html
