### ISSUE TITLE
Add FAQ entry about Sirius version

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#14]
![image](https://user-images.githubusercontent.com/64734/44083281-d5d09fea-9fb3-11e8-9325-99820fcf03f6.png)

**Comment by berezovskyi** [comment]
Okay, the issue seems that I have edited the model under Eclipse Photon (plugin install) and now can't open it under Oxygen (wanted ton run LyoD from code).

**Comment by berezovskyi** [comment]
Nothing to do with LyoD in particular

**Comment by berezovskyi** [comment]
Photon comes with Sirius 6

**Comment by jadelkhoury** [comment]
I think it is hard to avoid this problem. The message from Eclipse/Sirius is quite clear, but sure it is good to have an entry in a FAQ to explain it.

**Comment by yashkhatri** [comment]
@jadelkhoury Agree!

**Comment by berezovskyi** [comment]
Fixed in https://github.com/eclipse/lyo.designer/wiki/FAQ#q-internal-error-occurred-during-loading-models
