### ISSUE TITLE
 Allow client and server to be generated separately

### ISSUE THREAD

**Issue by sgarfinkel** [eclipse/lyo.designer#150]
I accidentally posted this in Lyo.Core: https://github.com/eclipse/lyo.core/issues/131

Currently, the client is generated as part of the entire server source code through the toolchain generator.

However they can be entirely decoupled and have no shared dependencies aside from the domains (which might be generated separately anyways). I've been manually moving the client after I regenerate it into a separate project, but I think it would be very helpful to be able to configure this in the generator directly.

**Comment by jadelkhoury** [comment]
Hi Sam

The generator does indeed support a client-only application. Have you tried deleting the ServiceProviderCatalog (and all its subelements), and then re-generate? Just make sure you keep the requiredAdaptors element, and its resources.
You should then get a Java application, that is not a web server.

Admittedly, LyoDesigner is biased towards servers. it offers very little generated code for a client. (But that's because it's a lot harder to guess what a client wants).
If you have any ideas how a client can be modelled, feel free to share.

**Comment by sgarfinkel** [comment]
Jad, I like the fact that it generates both but I would like to generate them into different locations as I've got a multi-module gradle project set up to build each component separately (domain, server, client).

**Comment by jadelkhoury** [comment]
I am not sure how clear the workshop instructions are (any feedback or suggestions for improvements appreciated), but I hope you already know that you can divide your code into different projects: Adapters (client or server) and  multiple specs.

But with this patch, you can even define the maven projects per Domain. (or for a bunch of domains).

**Comment by jadelkhoury** [comment]
Please ignore my previous comment, I thought we were discussing #151 here.
Anway, back to your issue here. 
You should be able to create different adaptors (hence projects) for each of your server and client. What doesn't work? 

Or is it a gradle specific issue?

**Comment by sgarfinkel** [comment]
So you'd recommend creating two toolchain models? That's fine, but how can I make the code generator _only_ generate server code or _only_ generate client code? Basically my current process is, run code generation then manually move the client code.

**Comment by jadelkhoury** [comment]
A single toolchain model can contain any number of clients, servers, and client/servers.

I have now expanded the sample toolchain to illustrate my point.
https://github.com/OSLC/lyo-adaptor-sample-modelling/tree/4.0.0-snapshot

- adaptor-client - is a client only application. it runs as any normal java application
- adaptor-rm-webapp - is a server only application
- adaptor-testing-webapp is a server application, that is also a client calling the adaptor-rm-webapp.

Is this what you had in mind?

**Comment by sgarfinkel** [comment]
Jad, this works perfectly for my use case.

**Comment by jadelkhoury** [comment]
Glad to hear.
