### ISSUE TITLE
Web.xml not generated

### ISSUE THREAD

**Issue by sgarfinkel** [eclipse/lyo.designer#151]
I accidentally posted this in Lyo.Core: https://github.com/eclipse/lyo.core/issues/130

Version: 4.0.0.202001221327

I am using the Lyo Standalone application.
 
I followed the [toolchain modelling workshop](https://oslc.github.io/developing-oslc-applications/eclipse_lyo/toolchain-modelling-workshop) as closely as possible, but no web.xml configuration is generated.

**Comment by jadelkhoury** [comment]
Just this morning, I released a patch to let LyoDesigner fully generate the whole adaptor. So not only will it generate the web.xml, but also the pom.xml. So you don't have to follow any instrunctions to setup a project.

See https://github.com/eclipse/lyo.designer/pull/149
As soon as I can get a review (@berezovskyi @jamsden) it will be released, and you should have this feature you are after.

**Comment by jadelkhoury** [comment]
For testing, I have now built a LyoDesigner application for this patch. If interested, you can download it from https://download.eclipse.org/lyo/product/binaries/superedge/

I would suggest you don't yet use it for your real model (unless of course you have backups). Just in case I make changes to the underlying metamodel of this patch, making it hard to revert any changes to the model.

**Comment by jadelkhoury** [comment]
Hi again
The changes from #149 are now released into master. If you want to use the latest version of LyoDesigner with this feature, you can direct the application to download updates from the following site: https://download.eclipse.org/lyo/product/p2/edge/

**Comment by sgarfinkel** [comment]
@jadelkhoury I think we can close this via #149?

**Comment by jadelkhoury** [comment]
Good to hear.
