### ISSUE TITLE
If the domain generation is not disabled, the domain package is ignored

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#154]
Error:(148,92) java: incompatible types: java.util.List<co.oslc.refimpl.rm.gen.resources.RequirementCollection> cannot be converted to java.util.List<org.eclipse.lyo.oslc.domains.rm.RequirementCollection>

Model: https://github.com/OSLC/refimpl/tree/master/model

**Comment by berezovskyi** [comment]
@jadelkhoury is this enough info?

**Comment by jadelkhoury** [comment]
Thanks. 
So this is another problem than what I had in mind. Will look into it. 
Word around: don’t disable the generation. Then just delete the whole “org” classes that gets generated. 

I was referring to the fact that Classes relating to the Vocab are wrongly generated into your adaptor. See https://github.com/OSLC/refimpl/tree/master/src/server-rm/src/main/java/co/oslc/refimpl/rm/gen/resources

**Comment by berezovskyi** [comment]
I may have done this with the legacy generation still present. I may have also had domains at commit https://github.com/eclipse/lyo.domains/commit/cca38945835b8d9cc17780e473e01b2f4d3b549a.

After a full migration to the new gen config and pulling the latest domains, seems to work just fine. May be hard for you to reproduce again.

**Comment by berezovskyi** [comment]
wontfix, can't reproduce
