### ISSUE TITLE
Lyo 4.0.0 Should Support Properties With Colliding Names

### ISSUE THREAD

**Issue by sgarfinkel** [eclipse/lyo.designer#160]
Currently, properties are referenced by their name globally. For example, the following fails to generate correctly:

```xml
<?xml version="1.0" encoding="ASCII"?>
<oslc4j_ai:Specification xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oslc4j_ai="http://org.eclipse.lyo/oslc4j/adaptorInterface">
  <domainSpecifications name="Domain2" namespaceURI="http://your.organisation.domain/nsp2#" namespacePrefix="//@domainPrefixes[name='nsp2']">
    <resources name="StringValue" resourceProperties="//@domainSpecifications[name='Domain2']/@resourceProperties[name='value']"/>
    <resources name="BooleanValue" resourceProperties="//@domainSpecifications[name='Domain2']/@resourceProperties[name='value']"/>
    <resourceProperties name="value" valueType="String"/>
    <resourceProperties name="value"/>
  </domainSpecifications>
  <domainPrefixes name="nsp2"/>
  <configuration xsi:type="oslc4j_ai:MavenSpecificationConfiguration">
    <generalConfiguration filesBasePath="." javaBasePackageName="your.basepackage.name"/>
    <projectConfiguration xsi:type="oslc4j_ai:MavenProjectConfiguration" lyoVersion="4.0.0-SNAPSHOT" groupId="your.basepackage.name" artifactId="oslc-specification" version="0.0.1-SNAPSHOT"/>
  </configuration>
</oslc4j_ai:Specification>
```

In that example, any usage of a particular `value` property will be generated as having a `String` type because that's the first `value` it finds. Instead, Lyo should assign a unique ID to each property and use those to capture ownership.

This is a major blocker for us, as the name of the property is also used in the associated generated ResourceShape.

**Comment by sgarfinkel** [comment]
Hi Jad,

I think the approach I proposed would work and resolve both issues. It’s similar to the way Ecore resolves references. Lyo could synthesize a unique ID for each property. And instead of using `/@domainSpecifications[name='Domain2']/@resourceProperties[name='value']` just use `/@domainSpecifications[name='Domain2']/@resourceProperties[id='<ID>'] `

**Comment by jadelkhoury** [comment]
Hi Sam

Yes. The trick is to work out a robust way to create this ID.

- It's a GUID, generated by the system, and out of control from the user.
- It has to be read-only, and preferably hidden from the GUI interface.
- When the user does a copy/past of the property, we have to produce a new GUID.
- (I don't even want to think about) When the user does a copy/past of a while EMF file, we have to produce new GUIDs for each item in the model.

Not rocket science, but I need to get under the hood with EMF generated code to put these things in place.
To illustrate, here are some loose threads I'm following to try to find something that works for us:
- https://www.eclipse.org/forums/index.php/t/440360/
- https://www.eclipse.org/forums/index.php/t/1095314/
- https://www.eclipse.org/forums/index.php/t/1068105/

**Comment by sgarfinkel** [comment]
It would require updates to the metamodel, but wouldn't the simplest solution to let ResourceProperties be contained by the associated Resource, rather than the current implementation where a ResourceProperty is a global singleton:

```xml
<resource name="Foo">
	<resourceProperty name="Bar" valueType="String"/>
</resource>
```

Then this maps more logically to the generated ResourceShape, since Java doesn't permit colliding names within the same scope anyways.

**Comment by berezovskyi** [comment]
@sgarfinkel Yes, but it collides with RDF that in no way requires properties to be bound to resources.

**Comment by berezovskyi** [comment]
I think this ticket would benefit from a minimal Turtle example to go forward clearly.

**Comment by jadelkhoury** [comment]
@berezovskyi Agree that we don't want to bound the properties to the resources. Although it is not intuitive to the user, who is most likely used to Class Diagram kind of models. I'd like to work on a more intuitive approach to help the user there, without necessarily changing the underlying metamodel. (But I'll leave that for another topic).

I believe i have a solution in sight based on those links I shared, but just need some time to put it together.

**Comment by berezovskyi** [comment]
@jadelkhoury If you make it look like a class diag, people assume it is a class diag. I think it will be best to show namespace prefix on both classes and properties in the Designer. E.g.

```
nsp2:MyClass
|_nsp2:title
|_dcterms:title
```

This will explain why two `nsp2:title` properties are the same across two classes but also explain how can one have multiple properties with the same (short) name on the same class.

**Comment by berezovskyi** [comment]
@jadelkhoury @sgarfinkel unless I am missing something, I tend to disagree with the approach to allow multiple properties with the same name under the same Domain Spec.

**Comment by jadelkhoury** [comment]
@berezovskyi It's not about  the properties allocated to a resource. This is working fine. It's about the list of Property constraints definined under  a certain domain. See for example the picture below.
It's a valid scenario where you want to have multiple constraints, but you want to give them the same name. For example, many resources want a "hasPart" relation, but their range points to different resources. Another example, is that you want to have dcterms:description constraint (Called description) of exactlyOne, while in the same domain you have a constraint that allows oneOrMany.
(Now it's time to read my first response above in this thread, to see how you can avoid this problem. But these workarounds are not so convenient).

![image](https://user-images.githubusercontent.com/7108694/81145659-fd7d9480-8f76-11ea-9884-88b6b06b11b5.png)

**Comment by berezovskyi** [comment]
@jadelkhoury true, this is a good counter-example, thank you. Maybe also worth to rename that Properties box in Domain Specs to Property Constraints or Shape Properties to make it clear that's not the same as Vocabulary properties? Also, we might want to still restrict multiple properties with the same name unless they point to a vocab property explicitly.

**Comment by jadelkhoury** [comment]
Good idea about the renaming.
I am actually working on this issue today, and I can see a light at the end of the dark EMF tunnel (more like a maze really).

>Also, we might want to still restrict multiple properties with the same name unless they point to a vocab property explicitly.

Pointing explicitly to an vocab property is still an uncommon case for most use cases. Not sure we want to enforce it for this peculiar reason. I'd rather we have a better establishing of the Vocab models before we put such restrictions.

**Comment by jadelkhoury** [comment]
For the record, the source of this problem is this earlier issue https://github.com/eclipse/lyo.designer/pull/72

**Comment by jadelkhoury** [comment]
@sgarfinkel ! I cannot add you as a reviewer of the https://github.com/eclipse/lyo.designer/pull/161 pullrequest I made that I hope will solve this problem. 

But I hope to build a patch, which you can then download and use from https://download.eclipse.org/lyo/product/p2/superedge/

Maybe you can check the new behaviour from this patch. But please work on some backup copy of your model, since the patch will do changes, and I am not 100% sure we are home yet.

I am pretty confident about the solution. The main concern now is how to ensure people can migrate easily in the case the models are composed of multiple files.

**Comment by jadelkhoury** [comment]
The other problem that I will leave for another issue is that the ID can now be changed by the user. I will need to make changes to Sirius to disable editions of this property (No out-fo-the-box support from Sirius :-()

**Comment by sgarfinkel** [comment]
Thank you @jadelkhoury I will review shortly!

**Comment by jadelkhoury** [comment]
Issue solved through https://github.com/eclipse/lyo.designer/pull/161
