### ISSUE TITLE
Lyo Designer unnecessarily generates classes for resources that are already generated from an external library

### ISSUE THREAD

**Issue by sgarfinkel** [eclipse/lyo.designer#164]
I have Lyo.Domains on my classpath as I am also extending the Architecture Management `Resource` in my Domain Model. The `Authentication Configuration` uses several resources such as `DctermsDomainConstants` which are provided by Lyo.Domains. Instead of using the instances that are provided by the classpath library, Lyo will instead regenerate a local copy of them:

![image](https://user-images.githubusercontent.com/10210461/81330678-6d227b00-906e-11ea-8fe6-d4dc35e24416.png)

This might be related to #120?

**Comment by jadelkhoury** [comment]
**The workaround**
In the lyo.domains model, check the "Configuration-->General-->do not generate" flag. This will stop generating all code in that model. But of course, you have done a local change, and don't push this change to the Lyo.Domains repo. 
Note that you can also disable generation per domainSpecs. But I assume you want to do it for the whole model. Hence, make sure you select the configuration that is part of the Diagram, and not inside any domain.

**Now to the future solution**
This is related to #120, but not exactly the same problem. Both are related to the complexity when the model is divided into multiple files. 
There are two scenarios we need to support, and I don't think LyoDesigner should exclude one over the other:
**Scenario1**: You breakdown your model into multiple files, but you want the generation to produce 1 single project.
**Scenario2**: you import models (like lyo.domains) which are already generated. So you don't want to generate that code again (but you want to model with them).

There is no way LyoDesigner can guess how the models are being used. The solution I am considering:
    Have a flag "Do not generate imported models" on each adaptor to instruct the generator to stop generating once it hits items not in the original file. A very coarse approach since it does not cover the case where you want to follow one set of models, but not others.  

Note that this is very similar to disabling generation from the Lyo.Domains side, but I guess the more complete approach is to give control from both ends of the models (the importer, and the importee).


Why I don't do this already? Besides times, I am not sure I want to add all these flags everywhere. Model configuration is getting complex as it is.

**Comment by sgarfinkel** [comment]
@jadelkhoury In that other issue Andrew suggested allowing users to mark domains as `External`. That seems like a reasonable solution to both problems in my opinion.

And your workaround has worked for me in the short-term, thanks!

**Comment by sgarfinkel** [comment]
For some reason it's still generating Vocabulary constants, which is strange. But otherwise the provided workaround prevents the dependent ResourceShapes from being generated.

**Comment by jadelkhoury** [comment]
Vocab generation is another unrelated problem, as reported under https://github.com/eclipse/lyo.designer/issues/157. Keep track of that. Hope to fix it soon.

**Comment by jadelkhoury** [comment]
@sgarfinkel Problem with the generation of Vocabulary constants should be solved now. 
Please pull the latest changes in Lyo.Domains plus the latest LyoDesigner.

**Comment by jadelkhoury** [comment]
@sgarfinkel have a look at this pull request that I hope will solve this problem
https://github.com/eclipse/lyo.designer/pull/167

**Comment by sgarfinkel** [comment]
Looks good, once this is merged I think we can close.
