### ISSUE TITLE
Allow "seeAlso" in Lyo Vocabulary Class/Property definitions to be multi-valued

### ISSUE THREAD

**Issue by sgarfinkel** [eclipse/lyo.designer#168]
Minor bug, but there are many RDF vocabularies that use the `rdfs:seeAlso` property multiple times on a particular RDF resource.

**Comment by jadelkhoury** [comment]
First, I think this is a issue for the lyo-domains and not LyoDesigner.

Now remember that rdfs:seeAlso is a vocabulary term, and it is really impossible to constraint its cardinality. Some scenarios might require exactly-one, while others require zero-or-many.

For this reason, in lyo-domains you should see the constraints on rdfs terms as examples. The main thing to borrow from there is the Vocabularies (See picture below), and consider instead defining your own constraints on these standard vocabularies.

So, just create your own ResourceProperty, and make sure its points to the SeeAlso property from Lyo-domains. How? set the PropertyDefinition property.

![image](https://user-images.githubusercontent.com/7108694/82825198-178e0100-9eab-11ea-9ff2-ad08a247ade9.png)

**Comment by sgarfinkel** [comment]
Hi Jad,

I think this is a bug in Lyo designer. To be more specific, the Vocabulary property "See Also" should be multivalued
![image](https://user-images.githubusercontent.com/10210461/82836028-bc9cdf80-9e93-11ea-9c66-e57e8063a4b5.png)

The Ecore metamodel just needs to be updated: https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.oslc4j.adaptormodel/model/vocabulary.ecore#L37

**Comment by jadelkhoury** [comment]
Hi sam,
Sorry forgot about this. OK, I get your point.

**Comment by jadelkhoury** [comment]
The latest version of LyoDesigner should solve this.
