### ISSUE TITLE
Bug in URL splitting logic

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#176]
When a URL slug is formed `{a}-{b}` and `{b}` contains `-` chars, the split is performed in a "greedy" way and only the last `-` is used to split.

Example: `SP-06d11754-d5db-4832-b6df-faba75a23732` gets split into `SP-06d11754-d5db-4832-b6df` and `faba75a23732`.

**Comment by jadelkhoury** [comment]
Are you referring to the case where the server is trying to resolve a uri and match it to a specific Jax-rs class & method? 

This is handled by JAX-RS. 

Is it also more appropriate to separate path parameters with “/“ instead of “-“

**Comment by berezovskyi** [comment]
I see. Seems like the only way to fix it is to define a regexp. I have instead used chars like '.' and '_'. I did not want slash in this particular case not to signal hierarchy.
