### ISSUE TITLE
When classes & property names use reserve names, RDF names get messed up too

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#18]
I have a resource shape _Object_ and a property _object_ in my domain spec. I expect instances to look like

    :o1 a ds:Object;
        ds:object "bla" .

The class generated for it is `DsObject` and the methods are is `getDsObject` & `setDsObject`. This is expected. But what I did not expect were the annotations for `DsObject` RDF Class & OSLC shape and the `dsObject` RDF property. I had to override the annotations as a workaround.

**Comment by yashkhatri** [comment]
@berezovskyi This is also merged in master. Can we close it?

**Comment by berezovskyi** [comment]
sure

@jadelkhoury can in future write "closes #18" anywhere in the commit message and the issue will be closed automatically once that pull request gets merged

**Comment by berezovskyi** [comment]
First, this is a legal class name that maps to

    <http://example.com/ns/crazy/Test%20Case> a rdfs:Class .

Not that I support doing anything close to that...

Second, I would just disallow some characters from a vocabulary class title instead of mangling them. This way, users will fail early in the process instead of scratching their head later down the road. Because I expect more people to use LyoD as I did to "mirror" an existing ontology. And they are in for a surprise if they attempt that.

**Comment by jadelkhoury** [comment]
fair enough. 
I would at the least need to fix the url-path, since a space there does not look good.
