### ISSUE TITLE
oslc.paging is not supported

### ISSUE THREAD

**Issue by midikiman** [eclipse/lyo.designer#203]
Resource services can append oslc.paging to requests, but have no way to consume that parameter as it's never passed in. Paging is therefore fixed as on or off for any given resource service. Resource service code should be updated to accept the oslc.paging boolean parameter and to respect its value.

**Comment by jadelkhoury** [comment]
Hi

So just to confirm, it is specifically the `oslc.paging` parameter you were missing? I can fix that.
Please also note that the current code also misses to properly handle the oslc.where and oslc.prefix parameters. On line 216, when constructing the nextPage url, I don't pass these 2 parameters. I will fix both problems in 1 commit.
https://github.com/OSLC/lyo-adaptor-sample-modelling/blob/ce49e88aed600b463bd8cc33dfb144b63a7667f1/adaptor-rm-webapp/src/main/java/com/sample/rm/services/ServiceProviderService1.java#L216

I duplicate the code here to give you a hint as to how to format code :-)
```
                httpServletRequest.setAttribute(OSLC4JConstants.OSLC4J_NEXT_PAGE,
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&oslc.pageSize=" + pageSize + "&page=" + (page + 1));

```

**Comment by midikiman** [comment]
Yes, it is specifically the "oslc.paging" QueryParam which is missing from the method signatures. The where and prefix parameters are already in there. The next page URL isn't my issue, but adding the where and prefix parameters to it is also necessary.

**Comment by jadelkhoury** [comment]
@midikiman! Please do an update based on the Edge update site.
Thanks for feedback.
