### ISSUE TITLE
SP info classes do not implement Serializable interface

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#28]
If the adaptor is ran on Docker, we need to sync the SP info between nodes. Lyo already provides two classes for it, a ServiceProvider and ???ServiceProviderInfo. The latter should be made serialisable to send its info over the network.

**Comment by jadelkhoury** [comment]
Why send this internal object SPInfo, when you can send a real OSLC/RDF resource - the ServiceProvider. 

There is already a QueryCapability GET method that returns all ServiceProviders (See method getServiceProviders() in class ServiceProviderService.java)
