### ISSUE TITLE
Empty factor class generated

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#29]
Is it normal for an empty factory class to be generated?

```java
public class TwinResourcesFactory {

    // Start of user code class_attributes
    // End of user code
    
    // Start of user code class_methods
    // End of user code

    //methods for DeviceRegistrationMessage resource
    

    //methods for PlanExecutionRequest resource
    

}
```

**Comment by jadelkhoury** [comment]
I can only produce constructors for resources that have a basicCapability defined.
Why? the property BasicCapability.instanceID is the only place that tells me how the ID of a resource is constructed. Any other capability does not have such information.

So, I assume your adaptor does not have such basicCapabilities?

**Comment by berezovskyi** [comment]
Correct

**Comment by jadelkhoury** [comment]
You have a real case. So, if you can think of factory methods to realistically create such resources, I can produce them. Otherwise, it's a "won't fix".

**Comment by berezovskyi** [comment]
Sorry for not being clear on the expected behaviour. I was expecting that class not to be generated at all if there is no methods to generate inside of it.

**Comment by jadelkhoury** [comment]
True. Can fix but I assume this is an obscure scenario and does not cause problems as it is. 
One argument to keep the file (besides the fact that I don’t want to write that extra If-statement all over the place) is that it is a placeholder dot the user-specific factory methods.

**Comment by berezovskyi** [comment]
Sounds reasonable, closing.
