### ISSUE TITLE
SP URI contructors are private

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#30]
Methods like

    xyz.servlet.ServiceProviderCatalogSingleton#constructXyzServiceProviderURI

are private. I need access to this method to register and unregister SPs on-the-fly.

**Comment by jadelkhoury** [comment]
Can you confirm that this is all that is needed for on-the-fly handling of SPs?

1. It looks to me that the public methods [de]registerServiceProvider should do the job you are after.

2. Alternatively, the method getServiceProviders() calls initServiceProviders() which in turns calls AdaptorManager.getServiceProviderInfos();
So, if you update the set of SPInfos in the manager, calling getServiceProviders also does the job?

**Comment by berezovskyi** [comment]
I think I have a better solution now. Please see the following commit: https://github.com/EricssonResearch/scott-eu/commit/630b28d102f2766ddf11a9c6dc3751b035b76d3b?diff=split#diff-6400b1e4377bcfceb12d8eee5cc8810eR130

The most relevant part to look at is the `initServiceProviders` method and the `‘createIndependentServiceProvider’` & `createTwinServiceProvider` methods refactored out of it.
