### ISSUE TITLE
Enhance underlying EMF meta-model and GUI to support SHACL shapes.

### ISSUE THREAD

**Issue by yashkhatri** [eclipse/lyo.designer#4]
This issue is related to Issue #3.

Enable creating a new SHACL Specification Diagram that contains tools for creating SHACL shapes.

**Comment by jadelkhoury** [comment]
@jamsden this is the first patch to start introducing SHACL models in Lyo Designer. 
Once more stable, you might want to review how we relate SHACL to OSLC?

**Comment by berezovskyi** [comment]
@jadelkhoury maybe we can do this automatically via https://github.com/eclipse/lyo.core/blob/13805559de034a44ce18eb9aeab25bfd75982a96/org.eclipse.lyo.shacl/src/main/java/org/eclipse/lyo/shacl/ShaclShapeFactory.java#L372

@jamsden is there an interest to enable discovery of SHACL shapes etc to make them a first-class citizen in OSLC 3.0?

**Comment by jamsden** [comment]
I have not heard of any interest in SHACL for current OSLC products. This 
is primarily because of a significant investment in ResourceShapes, and 
limited demand to change the underlying technology. 

Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by jadelkhoury** [comment]
@berezovskyi - In reply to your comment "maybe we can do this automatically via https://github.com/eclipse/lyo.core.../lyo/shacl/ShaclShapeFactory.java#L372"

Can you clarify? Not sure what "this" refers to. Nor what can be automated.

**Comment by berezovskyi** [comment]
I meant here the OSLC shapes could be converted into SHACL shapes automatically.

**Comment by yashkhatri** [comment]
Resolved Fixed!
