### ISSUE TITLE
Include oslc4j  core projects as plugins in lyo designer update site.

### ISSUE THREAD

**Issue by yashkhatri** [eclipse/lyo.designer#41]
Exporting Domain Model, Vocabulary Model and Tool Chain Model are dependent on projects in Lyo Core repository. Therefore, there's a need to include this projects as plugins in Lyo Designer update site.

**Comment by berezovskyi** [comment]
Is it really a blocker? See my comment on #42

**Comment by jadelkhoury** [comment]
Finally, managed to create osgi bundles from the oslc librarries.

**Comment by berezovskyi** [comment]
Sorry it took to long to merge in
