### ISSUE TITLE
OslcCoreMissingSetMethodException due to a regression in LyoD

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#61]
Resolving #15, there is a regression that causes the following exception from JMH:

`org.eclipse.lyo.oslc4j.core.exception.OslcCoreMissingSetMethodException: OSLC011: Missing corresponding set method for method getStep of class %Generated DS class%`

**Comment by berezovskyi** [comment]
I think the right thing to do here is to try rolling back the commit https://github.com/eclipse/lyo.designer/commit/137046a73834cf565dce7bddebe34a065957e12c

However, there was some refactoring associated with it and we might want to preserve that.

In the meanwhile, we can check if https://github.com/eclipse/lyo.core/pull/29 from @neormx can be extended to handle this case too.

Or we might consider breaking the signatures of the generated code in LyoD 4.0 and switch both "in" and "out" types to use a generic Set.

**Comment by berezovskyi** [comment]
cc @jadelkhoury

**Comment by berezovskyi** [comment]
@jamsden I know you don't like to break things :) But I think we can actually go all in and replace `HashSet` with a `Set` both in getters and setters in LyoD 4.0

**Comment by jamsden** [comment]
I suspect that is correct and preferred, but only in the interfaces. HashSet will still be needed in the implementations.

**Comment by berezovskyi** [comment]
Well, we are talking about method signatures here, not implementation. So, we can theoretically use Set all the way through.

The exception was caused by a mismatch between return type of the getter and the input type of the setter.

This mismatch was caused by us trying not to brake any existing generated code out there. If we switch the getter to a Set, the problem should go away.

No idea how did I miss it before when testing the original patch.

--
/Andrew

12 feb. 2019 kl. 21:15 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


I suspect that is correct and preferred, but only in the interfaces. HashSet will still be needed in the implementations.

**Comment by jadelkhoury** [comment]
@jamsden @berezovskyi Do we agree to go with the breaking change?

This issue is highlighted on https://forum.open-services.net/t/eclipse-lyo-2-4-error-when-posting-to-a-creation-factory/215/1

I can also reproduce it on any resource with a property of cardinality other than 1, upon unmarshalling. (marshelling does not seem to cause exceptions).

**Comment by berezovskyi** [comment]
Yes, I agree

--
/Andrew

16 mars 2019 kl. 00:04 skrev Jad El-khoury <notifications@github.com<mailto:notifications@github.com>>:


@jamsden<https://github.com/jamsden> @berezovskyi<https://github.com/berezovskyi> Do we agree to go with the breaking change?

This issue is highlighted on https://forum.open-services.net/t/eclipse-lyo-2-4-error-when-posting-to-a-creation-factory/215/1

I can also reproduce it on any resource with a property of cardinality other than 1, upon unmarshalling. (marshelling does not seem to cause exceptions).

**Comment by jadelkhoury** [comment]
Not sure if I did all that is required to connect the pull request #71 to this issue.
