### ISSUE TITLE
Register resources declaratively w/o Application class

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#63]
see https://www.vogella.com/tutorials/REST/article.html#first_servletdispatcher

**Comment by jadelkhoury** [comment]
I see this as an alternative. 
But Is there a benefit to make the change? Is there a problem with the current approach?

**Comment by berezovskyi** [comment]
There are pros and cons. Pros: no need to edit code to register/unregister; more control is given to the users. Cons: extra effort to get the adaptor running after code gen; the config may actually register different classes in different scenarios and that can cause pain to debug.

The current approach works just fine (at least for me).
