### ISSUE TITLE
Jersey warnings on void handlers

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#66]
`2464 [INFO] Errors - The following hints have been detected: HINT: A HTTP GET method, public void se.ericsson.cf.scott.sandbox.whc.services.ServiceProviderCatalogService.getHtmlServiceProvider(java.lang.String), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".
HINT: A HTTP GET method, public void se.ericsson.cf.scott.sandbox.whc.services.ServiceProviderService.getHtmlServiceProvider(java.lang.String), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".`

**Comment by jadelkhoury** [comment]
Since these methods eventually call RequestDispatcher::forward(), they will not be returning anything after that call (to forward()) is made.
The alternative is make the return type Response, but then I have to do "return null".

**Comment by jadelkhoury** [comment]
@berezovskyi unless you have a better suggestion, I suggest not to fix this.

**Comment by jadelkhoury** [comment]
Won’t fix
