### ISSUE TITLE
Add a version & timestamp to the Application class or index.jsp

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#81]
It would be good to have a comment, log message, or a notice in the JSP page with the LyoD version and time of generation, e.g.

```java
/**
 * Generated by Lyo Designer 4.0.0.201904250441 at 2019-05-09T13:30:29Z
 */
public class Application extends javax.ws.rs.core.Application {
...
}
```

**Comment by berezovskyi** [comment]
I think it would make debug much easier down the road. Both for devs and users.

**Comment by berezovskyi** [comment]
@jadelkhoury If you can create a Java class for me that you will query from Acceleo, I can implement the method to fetch the OSGi bundle version and format the UTC time string.

**Comment by jadelkhoury** [comment]
You seem to already have the code. Share that and I can just add it to the query. Less rounds.

**Comment by berezovskyi** [comment]
I don't, not yet :)

**Comment by jadelkhoury** [comment]
Ok. I see an issue with the feature. 
Everytime one generates, the Application.java file would be changed. Must be annoying if you have the file under version control.
Better to generate some some of readme file instead? This way, one can simply add it to .ignore list.

**Comment by berezovskyi** [comment]
No, I actually _want it to be under control._ :)

**Comment by jadelkhoury** [comment]
But I don't :-)

**Comment by berezovskyi** [comment]
For example, I have a problem. I look in the POM file and Lyo 2.4.0 is used. Hmm, what was the version of the generator. Are those versions compatible? You'll never know.

**Comment by berezovskyi** [comment]
In most cases, every generation triggers a change in 10+ files for me. A single line in the Application class is not even going to register.

**Comment by jadelkhoury** [comment]
but consider a simple regeneration where you did not even do anything. You will still get a change.
And for the need you mentioned, why can't you look in the readme file?

**Comment by berezovskyi** [comment]
We can remove the date and only write LyoD version into the comment. This way successive regenerations will not produce noise. Please don't touch my READMEs ;)

--
/Andrew
(from phone)



On Thu, May 9, 2019 at 8:54 PM +0200, "Jad El-khoury" <notifications@github.com<mailto:notifications@github.com>> wrote:


but consider a simple regeneration where you did not even do anything. You will still get a change.
And for the need you mentioned, why can't you look in the readme file?

**Comment by jadelkhoury** [comment]
I can live with that. But it does not have to me a "readme" file. we can call it LyoDesigner-generationlog. or something like that.
