### ISSUE TITLE
Created SPs are missing an identifier 

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#89]
An SP instance created from an SPInfo instance is missing an `identifier`:

<img width="1235" alt="Skärmavbild 2019-06-02 kl  22 05 30" src="https://user-images.githubusercontent.com/64734/58766758-91362c00-8582-11e9-9e61-cc4951f3f5ed.png">

I have been looking for a place where a regression might have occurred but can't find any. Maybe I fixed it by hand and it was overwritten by newly generated code and that's where the regression came from. This screenshot is from testing on RM Sample on the 4.0 branch.

**Comment by berezovskyi** [comment]
No recent changes to the SPFactory class in Core https://github.com/eclipse/lyo.core/commits/master/oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/core/model/ServiceProviderFactory.java

**Comment by berezovskyi** [comment]
Where we can fix it:

* `org.eclipse.lyo.oslc4j.core.model.ServiceProviderFactory#initServiceProvider` (look for `serviceProviderId` key in the `pathParameterValues)`
* Generated `%package%.servlet.ServiceProvidersFactory#createServiceProvider` (look for `serviceProviderId` key in the `pathParameterValues)`
* Generated `%package%.servlet.ServiceProviderCatalogSingleton#createServiceProvider` (set the identifier right before returning)

**Comment by berezovskyi** [comment]
Just noticed that the "about" field is also null. The real problem is that some fields are only set when the SP is registered (https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl#L261). Which is wrong (because this is not the place to modify an SP) and interferes with my ability to persist SPs or to generate them outside the SPC service lifecycle.

**Comment by jadelkhoury** [comment]
https://github.com/eclipse/lyo.designer/blob/cd72f1f99c42e5d893e8fe3bd7111c1525d990fe/org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl#L268

Is that what you are looking for? Surely, the SP will have a URI in the end, otherwise, the whole adaptor won't work!

**Comment by berezovskyi** [comment]
Yes, that's the one. I want to move that code to SP creation. Please review #90
