### ISSUE TITLE
New CI build is failing

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.designer#92]
> [ERROR] Cannot resolve project dependencies:
> [ERROR]   Software being installed: org.eclipse.lyo.oslc4j.adaptormodel 4.0.0.qualifier
> [ERROR]   Missing requirement: org.eclipse.lyo.oslc4j.adaptormodel 4.0.0.qualifier requires 'bundle org.eclipse.emf.ecore 0.0.0' but it could not be found

https://ci-staging.eclipse.org/lyo/job/lyo-designer-master/167/console
https://ci-staging.eclipse.org/lyo/job/lyo-designer-master/166/console

Last successful build:
https://ci-staging.eclipse.org/lyo/job/lyo-designer-master/165/console

**Comment by berezovskyi** [comment]
`git diff 16d945420c87df68bfbb53d43247ca7671580f3e..cd72f1f99c42e5d893e8fe3bd7111c1525d990fe`shows only 2 .mtl files changes. POM was not touched.

**Comment by berezovskyi** [comment]
Okay, it fails on my machine fast too:

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/64734/58901705-ffedc380-8701-11e9-8f0a-f8b9ee3f4d57.png">

**Comment by berezovskyi** [comment]
@jadelkhoury could you please take a look?

**Comment by berezovskyi** [comment]
Using newest Tycho and 2018-09 repos does not help:

		<tycho.version>1.4.0</tycho.version>
		<p2.repo>https://download.eclipse.org/releases/2018-09/201809191002/</p2.repo>

**Comment by jadelkhoury** [comment]
> Okay, it fails on my machine fast too:

Good then we can reproduce.  I will take a look. Every now and then, this problem re-appears but don’t manage to remember what the problems are.

**Comment by berezovskyi** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=521292 this thing implies the upstream p2 site is not declared correctly. This can't be true in our case.

**Comment by jadelkhoury** [comment]
I can build fine on my local machine (mvn clean package). Anything I can reset/clean to make the build closer to that on servers?

**Comment by berezovskyi** [comment]
Caused by Maven 3.6 upgrade. Reverted to 3.5 and pinned the version via Maven Wrapper. Will track the Tycho changelog for an upstream fix.

**Comment by berezovskyi** [comment]
Jad will commit the Maven Wrapper scripts and will close this issue.

**Comment by berezovskyi** [comment]
added a warning to https://github.com/eclipse/lyo.designer/wiki/Working-from-Source-Code
